Update Gulp.md: gulp-uglify cannot handle ES6+ syntax
Use [gulp-terser](https://www.npmjs.com/package/gulp-terser) instead of [gulp-uglify](https://www.npmjs.com/package/gulp-uglify). For example, the latter doesn't recognize ES6 [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals):
```
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected character '`'
```